version: "3.3"
services:
  ssh:
    build:
      context: ./
      args:
        - TIMEZONE
        - USERNAME
        - ROOT_PASSWORD
        - USER_PASSWORD
        - BANTIME
        - MAXRETRY
    image: "${SSH_IMAGE_NAME}:${SSH_IMAGE_TAG}"
    container_name: "${SSH_CONTAINER_NAME}"
    volumes:
      - ./config/.bashrc:/home/${USERNAME}/.bashrc
      - ./config/jail.local:/etc/fail2ban/jail.local
      - ./config/sshd_config:/etc/ssh/sshd_config
      - ./startup/startup.sh:/root/startup.sh
    restart: always
    privileged: true
    tty: true
    environment:
      DEBIAN_FRONTEND: noninteractive
    cap_add:
      - NET_ADMIN
    command: sudo /root/startup.sh
    ports:
      - "9001:80"
      - "${SSH_HOST_PORT}:${SSH_CONTAINER_PORT}"
